repos:
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.18.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.12.1]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

#- repo: https://github.com/ansys/pre-commit-hooks
#  rev: v0.3.1
#  hooks:
#    - id: add-license-headers
#      files: '(src|examples|tests|docker)/.*\.(py)|\.(proto)'
#      args:
#      - --start_year=2024

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.3
  hooks:
    - id: check-github-workflows


- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.5
  hooks:
    - id: ruff
      args: [--fix]
