FLOWKIT_PYTHON_API_KEY: flowkit-python-api-key
FLOWKIT_PYTHON_ENDPOINT: http://0.0.0.0:50052
FLOWKIT_PYTHON_WORKERS: 2
USE_SSL: False
#SSL_CERT_PUBLIC_KEY_FILE:
#SSL_CERT_PRIVATE_KEY_FILE:
EXTRACT_CONFIG_FROM_AZURE_KEY_VAULT: False
# AZURE_MANAGED_IDENTITY_ID: 
# AZURE_KEY_VAULT_NAME: 